import Database from 'better-sqlite3';
import { graphDriver } from './lib/neo4j.mjs';
import { extractDecisions } from './lib/llm.mjs';
const argv=process.argv.slice(2),limit=Number(argv.find(x=>x.startsWith('--limit='))?.split('=')[1])||Infinity,concurrency=Number(argv.find(x=>x.startsWith('--concurrency='))?.split('=')[1])||8;
const db=new Database('data/fishers.db'),driver=graphDriver();db.exec('CREATE TABLE IF NOT EXISTS decisions_log (file_id INTEGER NOT NULL, chunk_ordinal INTEGER NOT NULL, processed_at TEXT NOT NULL, status TEXT NOT NULL, error TEXT, PRIMARY KEY(file_id,chunk_ordinal))');
const normalizeId=value=>String(value||'').toUpperCase().replace(/[^A-Z0-9]/g,''); const person=value=>String(value||'').toLowerCase().replace(/[^a-z0-9 ]/g,'').replace(/\s+/g,' ').trim(); const status=value=>({APPROVED:'Approved',PASSED:'Approved',DENIED:'Denied',FAILED:'Denied',TABLED:'Tabled',CONTINUED:'Tabled',WITHDRAWN:'Withdrawn'})[String(value||'').toUpperCase()]||null;
const chunks=text=>text.length<=12000?[text]:Array.from({length:Math.ceil(text.length/10000)},(_,i)=>text.slice(i*10000,(i+1)*10000));
const files=db.prepare("SELECT file_id,name,plaintext FROM cc_files WHERE file_type='Minutes' AND length(trim(coalesce(plaintext,'')))>0 ORDER BY file_id").all().slice(0,limit),done=db.prepare("SELECT 1 FROM decisions_log WHERE file_id=? AND chunk_ordinal=? AND status='ok'"),log=db.prepare('INSERT OR REPLACE INTO decisions_log VALUES (?,?,?,?,?)');const units=files.flatMap(file=>chunks(file.plaintext).map((text,ordinal)=>({file,...file,text,ordinal}))).filter(unit=>!done.get(unit.file_id,unit.ordinal));let next=0,processed=0,failed=0,statusesSet=0,decisions=0;
async function save(session,fileId,item){const id=normalizeId(item.case_number);if(!id)return 0;const outcome=status(item.outcome),props={status:outcome,vote_ayes:Number.isInteger(item.ayes)?item.ayes:null,vote_nays:Number.isInteger(item.nays)?item.nays:null,vote_abstain:Number.isInteger(item.abstain)?item.abstain:null,opposition_present:item.opposition_present===true,decision_source_id:String(fileId),decision_source:'minutes',source:'minutes',source_id:String(fileId),extractor:'llm-decisions'};const match=await session.run("MATCH (c:Case) WITH c,replace(replace(replace(replace(toUpper(c.case_number),' ',''),'_',''),'.',''),'-','') AS normalized WHERE normalized=$id OR ($longId AND (normalized CONTAINS $id OR $id CONTAINS normalized)) SET c += $props RETURN c LIMIT 20",{id,longId:id.length>=6,props});let cases=match.records.map(r=>r.get('c'));if(!cases.length){const created=await session.run('MERGE (c:Case {case_number:$id}) SET c += $props RETURN c',{id,props:{...props,title:item.title||null,raw_number:item.case_number}});cases=created.records.map(r=>r.get('c'));}for(const c of cases){for(const [name,type] of [[item.moved_by,'MADE_MOTION'],[item.seconded_by,'SECONDED']])if(name&&person(name)){await session.run(`MERGE (p:Person {name_normalized:$key}) SET p.name=$name MERGE (p)-[r:${type}]->(c) SET r.source='minutes',r.source_id=$source_id,r.extractor='llm-decisions',r.outcome=$outcome`,{key:person(name),name,source_id:String(fileId),outcome});}}return outcome?cases.length:0;}
async function worker(){const session=driver.session();try{while(next<units.length){const unit=units[next++];try{const result=await extractDecisions(unit.text);for(const item of result.decisions||[]){decisions++;statusesSet+=await save(session,unit.file_id,item);}log.run(unit.file_id,unit.ordinal,new Date().toISOString(),'ok',null);processed++;}catch(error){log.run(unit.file_id,unit.ordinal,new Date().toISOString(),'error',String(error.message).slice(0,300));failed++;}if((processed+failed)%10===0)console.log(`decisions progress ${processed+failed}/${units.length}`);}}finally{await session.close();}}
try{console.log(`decision extracting ${units.length} minutes chunks with concurrency ${concurrency}`);await Promise.all(Array.from({length:Math.min(concurrency,units.length||1)},worker));console.log(JSON.stringify({files:files.length,processed,failed,decisions,statuses_set:statusesSet},null,2));}finally{db.close();await driver.close();}
