import Database from 'better-sqlite3';
import { graphDriver, counts } from './lib/neo4j.mjs';
import { extractOpen } from './lib/llm.mjs';
const argv=process.argv.slice(2),limit=Number(argv.find(x=>x.startsWith('--limit='))?.split('=')[1])||Infinity,concurrency=Number(argv.find(x=>x.startsWith('--concurrency='))?.split('=')[1])||12,extractor='llm-open';
const db=new Database('data/fishers.db'),driver=graphDriver();db.exec('CREATE TABLE IF NOT EXISTS graph_extract_log (source_id TEXT NOT NULL, chunk_ordinal INTEGER NOT NULL, extractor TEXT NOT NULL, processed_at TEXT NOT NULL, status TEXT NOT NULL, error TEXT, PRIMARY KEY(source_id,chunk_ordinal,extractor))');
const chunks=text=>{const out=[];for(let start=0,ordinal=0;start<text.length;start+=5400,ordinal++)out.push({ordinal,text:text.slice(start,start+6000),char_start:start});return out;};
const safe=value=>{const v=String(value||'').replace(/[^A-Za-z0-9_]+/g,'_').replace(/_+/g,'_').replace(/^_+|_+$/g,'').slice(0,40);return /^[A-Za-z]/.test(v)?v:'';}; const q=v=>'`'+v.replace(/`/g,'')+'`';
function props(input,ctx){const out={};for(const [k,v] of Object.entries(input||{})){const key=safe(k);if(!key||v==null)continue;out[key]=Array.isArray(v)?(v.every(x=>x==null||typeof x!=='object')?v.filter(x=>x!=null):JSON.stringify(v)):typeof v==='object'?JSON.stringify(v):v;}out.source=ctx.source;out.source_id=String(ctx.source_id);out.extractor=extractor;out.confidence=out.confidence??.8;if(ctx.start_seconds!=null)out.start_seconds=ctx.start_seconds;if(out.char_start!=null)out.char_start+=ctx.char_start||0;if(out.char_end!=null)out.char_end+=ctx.char_start||0;return out;}
async function ensureDocument(s,ctx){await s.run('MERGE (d:Document {doc_id:$id}) SET d.source=$source,d.source_id=$source_id,d.title=$title,d.url=$url,d.extractor=$extractor,d.confidence=1.0',{id:ctx.doc_id,source:ctx.source,source_id:String(ctx.source_id),title:ctx.title,url:ctx.url||null,extractor});}
async function load(s,result,ctx){const emitted=new Set();for(const node of result.nodes||[]){const label=safe(node.label),key=String(node.key||'').trim();if(!label||!key)continue;await s.run(`MERGE (n:OpenEntity {name:$key}) SET n:${q(label)} SET n += $props`,{key,props:{...props(node.props,ctx),name:key,dynamic_label:label}});emitted.add(key);}for(const rel of result.relationships||[]){const type=safe(rel.type),from=String(rel.from?.key||'').trim(),to=String(rel.to?.key||'').trim();if(!type||!from||!to||!emitted.has(from)||!emitted.has(to))continue;await s.run(`MATCH (a:OpenEntity {name:$from}),(b:OpenEntity {name:$to}) MERGE (a)-[r:${q(type)}]->(b) SET r += $props`,{from,to,props:props(rel.props,ctx)});}for(const name of emitted)await s.run('MATCH (n:OpenEntity {name:$name}),(d:Document {doc_id:$doc}) MERGE (n)-[r:MENTIONED_IN {source_id:$source_id}]->(d) SET r.source=$source,r.start_seconds=$start,r.extractor=$extractor,r.confidence=1.0',{name,doc:ctx.doc_id,source_id:String(ctx.source_id),source:ctx.source,start:ctx.start_seconds??null,extractor});return emitted.size;}
function transcriptUnits(){const rows=db.prepare('SELECT video_id,start_seconds,text FROM yt_transcript_cues ORDER BY video_id,sort_order').all(),by=new Map();for(const r of rows){if(!by.has(r.video_id))by.set(r.video_id,[]);by.get(r.video_id).push(r);}const out=[];for(const [video_id,cues] of by){let text='',offsets=[];for(const cue of cues){offsets.push({at:text.length,start:cue.start_seconds});text+=`${cue.text}\n`;}for(const chunk of chunks(text)){const loc=[...offsets].reverse().find(x=>x.at<=chunk.char_start)||offsets[0];out.push({...chunk,source:'transcript',source_id:video_id,doc_id:`video:${video_id}`,title:`YouTube transcript ${video_id}`,url:`https://www.youtube.com/watch?v=${video_id}`,start_seconds:loc?.start});}}return out;}
const files=db.prepare("SELECT file_id source_id,file_type,name title,stream_url url,plaintext text FROM cc_files WHERE length(trim(coalesce(plaintext,'')))>0 AND file_type IN ('Minutes','Agenda Packet') ORDER BY CASE file_type WHEN 'Minutes' THEN 0 ELSE 1 END,file_id").all().flatMap(r=>chunks(r.text).map(c=>({...r,...c,source:r.file_type==='Minutes'?'minutes':'packet',doc_id:`file:${r.source_id}`})));const doneStmt=db.prepare("SELECT 1 FROM graph_extract_log WHERE source_id=? AND chunk_ordinal=? AND extractor=? AND status='ok'"),pending=[...files,...transcriptUnits()].filter(u=>!doneStmt.get(String(u.source_id),u.ordinal,extractor)).slice(0,limit===Infinity?undefined:limit),log=db.prepare('INSERT OR REPLACE INTO graph_extract_log VALUES (?,?,?,?,?,?)');let next=0,ok=0,fail=0,emitted=0;
async function worker(){const s=driver.session();try{while(next<pending.length){const unit=pending[next++];try{await ensureDocument(s,unit);emitted+=await load(s,await extractOpen(unit.text),unit);log.run(String(unit.source_id),unit.ordinal,extractor,new Date().toISOString(),'ok',null);ok++;}catch(error){log.run(String(unit.source_id),unit.ordinal,extractor,new Date().toISOString(),'error',String(error.message).slice(0,300));fail++;}if((ok+fail)%25===0)console.log(`open extract progress ${ok+fail}/${pending.length} (ok=${ok} fail=${fail})`);}}finally{await s.close();}}
try{console.log(`open extracting ${pending.length} chunks with concurrency ${concurrency}`);await Promise.all(Array.from({length:Math.min(concurrency,pending.length||1)},worker));console.log(JSON.stringify({processed:ok,emitted_nodes:emitted,failed:fail,counts:await counts(driver)},null,2));}finally{db.close();await driver.close();}
