const normalize = (value) => String(value || "").toLowerCase().trim().replace(/\s+/g, " ");
const status = (value) => { const s = String(value || "").toLowerCase(); return s.includes("approv") ? "APPROVED" : s.includes("withdraw") ? "WITHDRAWN" : s.includes("den") || s.includes("reject") ? "DENIED" : s.includes("table") || s.includes("continu") ? "TABLED" : "PENDING"; };
const terminal = (value) => ["APPROVED", "DENIED", "WITHDRAWN", "TABLED"].includes(status(value));
const caseId = (value) => String(value || "").toUpperCase().replace(/[\s_.-]+/g, "");
const landUse = (row) => /^(RZ|PUD|VA|SE|ANX|TA|SUP|DP|PC)-?\d/i.test(String(row.case_number || "")) || /(rezon|varianc|pud|annex|special[ -]?exception|plat)/i.test(String(row.case_type || ""));
const distance = (a, b) => { const x = normalize(a), y = normalize(b), dp = Array.from({ length: y.length + 1 }, (_, i) => i); for (let i = 1; i <= x.length; i++) { let prior = dp[0]++; for (let j = 1; j <= y.length; j++) { const current = dp[j]; dp[j] = Math.min(dp[j] + 1, dp[j - 1] + 1, prior + (x[i - 1] === y[j - 1] ? 0 : 1)); prior = current; } } return dp[y.length]; };
const number = (value) => typeof value?.toNumber === "function" ? value.toNumber() : Number(value || 0);
const plain = (record) => Object.fromEntries(Object.entries(record.toObject()).map(([key, value]) => [key, Array.isArray(value) ? value.map((item) => typeof item?.toNumber === "function" ? item.toNumber() : item) : typeof value?.toNumber === "function" ? value.toNumber() : value]));
const languagePrompt = "You receive Cypher-computed civic facts as JSON. Return only JSON. You may phrase supplied facts, but never introduce a number or name absent from the facts. Cite provided case_numbers in every item. Never infer vote direction.";

export async function narrate(facts, task) {
  if (process.env.ALLOW_SLOW_LLM !== "1") throw new Error("LLM narration is snapshot-only");
  const body = JSON.stringify({ task, facts });
  if (process.env.OPENROUTER_API_KEY) {
    const response = await fetch("https://openrouter.ai/api/v1/chat/completions", { method: "POST", headers: { Authorization: `Bearer ${process.env.OPENROUTER_API_KEY}`, "Content-Type": "application/json", "X-Title": "Sentinel Intelligence Engine", "HTTP-Referer": "https://github.com/local/sentinel" }, body: JSON.stringify({ model: process.env.OPENROUTER_MODEL || "deepseek/deepseek-v4-flash", reasoning: { enabled: false }, response_format: { type: "json_object" }, messages: [{ role: "system", content: languagePrompt }, { role: "user", content: body }] }) });
    if (!response.ok) throw new Error(`LLM http_${response.status}`); const payload = await response.json(); return JSON.parse(String(payload.choices?.[0]?.message?.content || "{}").replace(/^```json\s*|\s*```$/g, ""));
  }
  throw new Error("LLM provider unavailable");
}

async function evidence(session, cases) {
  const result = await session.run("MATCH (c:Case)-[:EVIDENCED_BY]->(d:Document) WHERE c.case_number IN $cases RETURN c.case_number AS case_number,d.doc_id AS doc_id,d.title AS title,d.url AS url LIMIT 40", { cases });
  const rows = result.records.map(plain); return cases.map((case_number) => rows.find((row) => row.case_number === case_number) || { case_number, doc_id: null, title: `Case ${case_number}`, url: null });
}

export async function findings(driver) {
  const session = driver.session();
  try {
    // A Neo4j session runs one query at a time; run these sequentially (not Promise.all on one session).
    const repeatResult = await session.run("MATCH (o)-[:APPLICANT_FOR]->(c:Case) WHERE (o:Organization OR o:Person) AND o.name IS NOT NULL RETURN o.name AS name,labels(o)[0] AS kind,collect(DISTINCT {case_number:c.case_number,status:c.status,case_type:c.case_type}) AS case_rows LIMIT 200");
    const attorneyResult = await session.run("MATCH (a:Person)-[:REPRESENTS]->(x)-[:APPLICANT_FOR]->(c:Case) WHERE a.name IS NOT NULL RETURN a.name AS attorney,collect(DISTINCT {case_number:c.case_number,status:c.status,case_type:c.case_type}) AS case_rows LIMIT 200");
    // Chosen join: Case and Sentiment share extraction source_id. It returns rows; the Document/MENTIONED_IN join does not.
    const oppositionResult = await session.run("MATCH (c:Case),(s:OpenEntity:Sentiment) WHERE c.source_id=s.source_id AND toLower(coalesce(c.status,'')) CONTAINS 'approv' RETURN c.case_number AS case_number,c.status AS status,c.case_type AS case_type,collect(DISTINCT coalesce(s.name,s.text,s.sentiment,'opposition')) AS sentiments LIMIT 25");
    const terminalResult = await session.run("MATCH (c:Case) RETURN c.case_number AS case_number,c.status AS status,c.case_type AS case_type");
    const group = (rows, field) => { const map = new Map(); for (const raw of rows.map(plain)) { const key = normalize(raw[field]); if (!key) continue; const current = map.get(key) || { name: raw[field], case_rows: new Map() }; raw.case_rows.filter(landUse).forEach((item) => current.case_rows.set(caseId(item.case_number), item)); map.set(key, current); } const groups = [...map.values()].map((item) => { const rows = [...item.case_rows.values()]; return { name: item.name, case_numbers: rows.map((row) => row.case_number), total: rows.length, decided: rows.filter((row) => terminal(row.status)).length, approved: rows.filter((row) => status(row.status) === "APPROVED").length }; }).filter((item) => item.total >= 2); for (const item of groups) for (const other of groups) if (item !== other && item.total >= other.total && distance(item.name, other.name) <= 1) { item.case_numbers = [...new Set([...item.case_numbers, ...other.case_numbers])]; item.total = item.case_numbers.length; other.total = 0; } return groups.filter((item) => item.total >= 2).sort((a, b) => b.total - a.total); };
    const repeats = group(repeatResult.records, "name").slice(0, 4).map((item, index) => ({ id: `repeat-${index}`, type: "repeat_applicant", entity: item.name, stat: `${item.total} linked cases`, cases: item.total, case_numbers: item.case_numbers.slice(0, 10) }));
    const attorneys = group(attorneyResult.records, "attorney").slice(0, 4).map((item, index) => ({ id: `attorney-${index}`, type: "attorney_rate", entity: item.name, stat: item.decided ? `${item.approved} of ${item.decided} decided cases approved` : `${item.total} cases represented`, approved: item.approved, total: item.total, decided: item.decided, case_numbers: item.case_numbers.slice(0, 10) }));
    const terminalCases = terminalResult.records.map(plain).filter((item) => landUse(item) && terminal(item.status)), baseApproved = terminalCases.filter((item) => status(item.status) === "APPROVED").length, baseRate = terminalCases.length ? baseApproved / terminalCases.length : 0;
    const outliers = [...group(repeatResult.records, "name"), ...group(attorneyResult.records, "attorney")].filter((item) => item.decided >= 2 && Math.abs(item.approved / item.decided - baseRate) >= .2).sort((a, b) => Math.abs(b.approved / b.decided - baseRate) - Math.abs(a.approved / a.decided - baseRate)).slice(0, 3).map((item, index) => ({ id: `outlier-${index}`, type: "approval_outlier", entity: item.name, stat: `${item.approved} of ${item.decided} decided cases approved vs ${Math.round(100 * baseRate)}% overall`, approved: item.approved, decided: item.decided, baseRate: Math.round(100 * baseRate), case_numbers: item.case_numbers.slice(0, 10) }));
    const opposition = oppositionResult.records.map(plain).filter((item) => landUse(item) && status(item.status) === "APPROVED").slice(0, 4).map((item, index) => ({ id: `opposition-${index}`, type: "approved_despite_opposition", entity: item.case_number, stat: `Approved with ${item.sentiments.length} linked opposition signal${item.sentiments.length === 1 ? "" : "s"}`, sentiments: item.sentiments.slice(0, 3), case_numbers: [item.case_number] }));
    const facts = [...repeats, ...attorneys, ...opposition, ...outliers].slice(0, 12);
    let language = {}; try { language = await narrate(facts, "For each fact return findings:[{id,headline,why}]. Headline and why must only rephrase supplied fields and must include a case_number."); } catch { language = { findings: [] }; }
    const prose = new Map((language.findings || []).map((item) => [item.id, item]));
    // Evidence lookups reuse the one session, so run them sequentially too.
    const out = [];
    for (const item of facts) out.push({ type: item.type, headline: prose.get(item.id)?.headline || `${item.entity}: ${item.stat}`, why: prose.get(item.id)?.why || `Cases: ${item.case_numbers.join(", ")}.`, stat: item.stat, case_numbers: item.case_numbers, entities: [item.entity], evidence: await evidence(session, item.case_numbers) });
    return out;
  } finally { await session.close(); }
}

export async function predict(driver, input) { const session = driver.session(); try { const current = input.case ? (await session.run("MATCH (c:Case {case_number:$case}) RETURN c LIMIT 1", { case: input.case })).records[0]?.get("c") : null; const props = current?.properties || input; const comparable = await session.run("MATCH (c:Case) WHERE c.case_number <> $case AND (toLower(coalesce(c.status,'')) CONTAINS 'approv' OR toLower(coalesce(c.status,'')) CONTAINS 'withdraw' OR toLower(coalesce(c.status,'')) CONTAINS 'den' OR toLower(coalesce(c.status,'')) CONTAINS 'reject') RETURN c.case_number AS case_number,c.status AS status,c.case_type AS case_type LIMIT 40", { case: props.case_number || input.case || "" }); const precedents = comparable.records.map(plain).slice(0, 12); const approved = precedents.filter((item) => status(item.status) === "APPROVED").length; const facts = { requested_case: props.case_number || null, factors: { case_type: props.case_type || input.case_type || null, applicant: input.applicant || null, has_staff_recommendation: input.has_staff_recommendation ?? null, opposition_count: input.opposition_count ?? null }, precedents, approval_rate: precedents.length ? Math.round(100 * approved / precedents.length) : 0, approved, total: precedents.length }; let narrative; try { narrative = await narrate(facts, "Return {forecast,reasoning,precedent_case_numbers}. Forecast and reasoning may only use facts and cite at least two provided case_numbers."); } catch { narrative = { forecast: `Comparable approval rate: ${facts.approval_rate}% (${approved}/${precedents.length}).`, reasoning: `Precedents: ${precedents.slice(0, 3).map((item) => item.case_number).join(", ")}.`, precedent_case_numbers: precedents.slice(0, 3).map((item) => item.case_number) }; } return { ...facts, ...narrative, evidence: await evidence(session, precedents.slice(0, 5).map((item) => item.case_number)) }; } finally { await session.close(); } }

export async function near(driver, db, address) { const requested = String(address || "").trim(); const parcel = db?.prepare("SELECT parcel_no,local_address,subdiv_name,prop_class FROM parcels WHERE local_address = ? COLLATE NOCASE LIMIT 1").get(requested) || db?.prepare("SELECT parcel_no,local_address,subdiv_name,prop_class FROM parcels WHERE local_address LIKE ? COLLATE NOCASE ORDER BY length(local_address) LIMIT 1").get(`${requested}%`); if (!parcel) return { parcel: null, cases: [], briefing: "No matching Fishers parcel was found.", draft_comment: "" }; const session = driver.session(); try { const rows = await session.run("MATCH (c:Case)-[:CONCERNS]->(p:Parcel) WHERE toLower(coalesce(p.address,'')) CONTAINS toLower($token) RETURN DISTINCT c.case_number AS case_number,c.status AS status,c.title AS title LIMIT 12", { token: String(parcel.local_address).split(" ").slice(0, 2).join(" ") }); const cases = rows.records.map(plain); const facts = { parcel, heuristic: "shared leading street-address tokens on Parcel.address", cases }; let narrative; try { narrative = await narrate(facts, "Return {briefing,draft_comment,case_numbers}. Use only provided cases; cite case_numbers. The comment must be a draft for a resident."); } catch { narrative = { briefing: cases.length ? `Related cases near ${parcel.local_address}: ${cases.map((item) => item.case_number).join(", ")}.` : `No graph-linked cases were found near ${parcel.local_address}.`, draft_comment: cases.length ? `I am writing about ${cases[0].case_number} near ${parcel.local_address}. Please address neighborhood impacts and provide a public response.` : "" }; } return { parcel, cases, ...narrative, evidence: await evidence(session, cases.map((item) => item.case_number)) }; } finally { await session.close(); } }
