import OpenAI from 'openai';
import { env } from './env.mjs';
const schema={type:'object',properties:{nodes:{type:'array',items:{type:'object',properties:{label:{type:'string'},key:{type:'string'},props:{type:'object'}},required:['label','key','props']}},relationships:{type:'array',items:{type:'object',properties:{type:{type:'string'},from:{type:'object'},to:{type:'object'},props:{type:'object'}},required:['type','from','to','props']}}},required:['nodes','relationships']};
const prompt=(text)=>`Extract only explicit Fishers civic entities and relationships. Allowed node labels: Meeting, Case, Parcel, ZoningDistrict, Person, Organization, Document. Allowed relations: HEARD_AT, CONCERNS, REZONE_FROM, REZONE_TO, APPLICANT_FOR, REPRESENTS, SPOKE_AT, MADE_MOTION, VOTED, CURRENTLY_ZONED, OWNED_BY, HAS_DOCUMENT, EVIDENCED_BY. Include exact source offsets and do not infer. Text:\n${text}`;
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const stripFences=value=>value.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim();
const openInstruction='Extract ALL salient entities and the relationships between them from this local-government text. You choose the entity types (labels) and relationship types that best fit — do NOT restrict to a fixed schema. Capture things a civic analyst would care about: projects, budgets/dollar amounts, dates/deadlines, conditions of approval, staff recommendations, ordinances, policies, locations, organizations, people and their roles, public comments/sentiment, and any domain concept present. Respond ONLY with JSON of shape {"nodes":[{"label":<PascalCase type>,"key":<canonical name/identifier>,"props":{...}}],"relationships":[{"type":<UPPER_SNAKE_CASE verb>,"from":{"label":..,"key":..},"to":{"label":..,"key":..},"props":{...}}]}. Use only what is explicit in the text; never invent. Keep labels/types concise and reusable across documents.';
async function call(text,instruction,name){const e=env(),provider=e.LLM_PROVIDER||'gemini';if(provider==='openrouter'){if(!e.OPENROUTER_API_KEY)throw new Error('OPENROUTER_API_KEY is required when LLM_PROVIDER=openrouter');let last;for(let attempt=0;attempt<3;attempt++){try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),120000);const r=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',signal:controller.signal,headers:{Authorization:`Bearer ${e.OPENROUTER_API_KEY}`,'Content-Type':'application/json','X-Title':'Fishers Civic Graph','HTTP-Referer':'https://github.com/local/sentinel'},body:JSON.stringify({model:e.OPENROUTER_MODEL||'deepseek/deepseek-v4-flash',reasoning:{enabled:false},response_format:{type:'json_object'},messages:[{role:'system',content:instruction},{role:'user',content:text}]})});clearTimeout(timer);const body=await r.text();if(r.ok)return JSON.parse(stripFences(JSON.parse(body).choices?.[0]?.message?.content||''));if(r.status!==429&&r.status<500)throw new Error(`OpenRouter extraction failed (${r.status}): ${body.slice(0,300)}`);last=new Error(`OpenRouter extraction failed (${r.status}): ${body.slice(0,300)}`);}catch(error){last=error;if(attempt===2)throw error;}await sleep(500*2**attempt);}throw last;}if(provider==='openai'){if(!e.OPENAI_API_KEY)throw new Error('OPENAI_API_KEY is required when LLM_PROVIDER=openai');const c=new OpenAI({apiKey:e.OPENAI_API_KEY});const r=await c.responses.create({model:e.OPENAI_MODEL||'gpt-5.6',input:`${instruction}\n\n${text}`,text:{format:{type:'json_schema',name,strict:true,schema}}});return JSON.parse(r.output_text);}if(!e.GEMINI_API_KEY)throw new Error('GEMINI_API_KEY is required when LLM_PROVIDER=gemini');const url=`https://generativelanguage.googleapis.com/v1beta/models/${e.GEMINI_MODEL||'gemini-2.0-flash'}:generateContent?key=${e.GEMINI_API_KEY}`;const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:`${instruction}\n\n${text}`}]}],generationConfig:{responseMimeType:'application/json',responseSchema:schema}})});if(!r.ok){const body=await r.text();if(r.status===429&&(/limit:\s*0|RESOURCE_EXHAUSTED/i.test(body)))throw new Error('Gemini key has no free-tier quota — enable billing, use an AI Studio key, or set LLM_PROVIDER=openai with OPENAI_API_KEY');throw new Error(`Gemini extraction failed (${r.status}): ${body.slice(0,500)}`);}return JSON.parse((await r.json()).candidates?.[0]?.content?.parts?.[0]?.text||'{}');}
export const extract=text=>call(text,prompt('').replace(/Text:\s*$/,'')+' Respond ONLY with the specified JSON shape and use only allowed labels and relations.', 'graph_extract');
export const extractOpen=text=>call(text,openInstruction,'graph_open_extract');
const decisionsInstruction="From these meeting minutes, extract every agenda item that received a decision or vote. Return JSON {decisions:[{case_number,title,outcome,ayes,nays,abstain,moved_by,seconded_by,opposition_present}]}. case_number = the docket/ordinance/resolution/case identifier as written (e.g. RZ-26-1, PUD-25-17, Ordinance 012026C); outcome = one of APPROVED, DENIED, TABLED, CONTINUED, WITHDRAWN, PASSED, FAILED, or null if none stated; ayes/nays/abstain = integer vote counts if a roll-call or tally is stated else null; moved_by/seconded_by = councilor names if stated; opposition_present = true if any member of the public spoke or wrote against it. Extract only what is explicitly stated; never infer. Respond only with the JSON object.";
export const extractDecisions=text=>call(text,decisionsInstruction,'minutes_decisions');
